export const ADD_TODO = 'ADD_TODO'
export const REMOVE_TODO = 'REMOVE_TODO'
export const UPDATE_TODO = 'UPDATE_TODO'
export const REMOVE_COMPLETED = 'REMOVE_COMPLETED'
export const TOGGLE_ALL = 'TOGGLE_ALL'
export const UPDATE_FILTER = 'UPDATE_FILTER'
